import { Product } from "@/types";

const baseProducts: Product[] = [
  {
    id: "1",
    slug: "organic-cotton-bodysuit",
    name: "Organic Cotton Bodysuit",
    description:
      "Ultra-soft 100% organic cotton bodysuit with snap closures. Gentle on sensitive newborn skin. Machine washable and hypoallergenic — perfect for everyday wear.",
    price: 24,
    category: "body",
    colors: ["White", "Sage", "Sand", "Sky Blue"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    emoji: "🌿",
    cardColor: "#C8DDD8",
  },
  {
    id: "2",
    slug: "cloud-print-blanket",
    name: "Cloud Print Blanket",
    description:
      "Dreamy cloud-patterned cotton blanket, ultra-soft and breathable. Perfect for swaddling, strolling, and cozy nap times. Generous size for growing babies.",
    price: 48,
    category: "blanket",
    colors: ["White & Blue", "White & Sage", "White & Sand"],
    sizes: ["80×100 cm", "100×120 cm"],
    emoji: "☁️",
    cardColor: "#C4D4E4",
  },
  {
    id: "3",
    slug: "hospital-exit-set",
    name: "Hospital Exit Set",
    description:
      "Complete 5-piece set for your precious homecoming day: bodysuit, romper, hat, mittens, and socks. Made from the softest organic cotton for delicate newborn skin.",
    price: 89,
    category: "set",
    colors: ["White", "Sage", "Sand"],
    sizes: ["0-1 Month", "1-3 Months"],
    emoji: "🎀",
    cardColor: "#D0E0CC",
    isNew: true,
  },
  {
    id: "4",
    slug: "bamboo-hooded-towel",
    name: "Bamboo Hooded Towel",
    description:
      "Luxuriously soft bamboo-cotton blend hooded towel. Highly absorbent and gentle on delicate skin. The adorable hood keeps baby warm and cozy after every bath.",
    price: 38,
    category: "towel",
    colors: ["White", "Cream", "Sage", "Sand"],
    sizes: ["70×70 cm", "90×90 cm"],
    emoji: "🛁",
    cardColor: "#E4D8C4",
  },
  {
    id: "5",
    slug: "bear-ear-romper",
    name: "Bear Ear Romper",
    description:
      "Adorable bear ear hooded romper made from premium cotton fleece. Keeps baby warm and irresistibly cute. Easy snap closures make diaper changes quick and simple.",
    price: 42,
    category: "romper",
    colors: ["Beige", "Sage", "Blue", "Lavender"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months", "12-18 Months"],
    emoji: "🐻",
    cardColor: "#D4CAE4",
    isNew: true,
  },
  {
    id: "6",
    slug: "mini-bunny-backpack",
    name: "Mini Bunny Backpack",
    description:
      "A precious little bunny-shaped backpack for toddlers. Perfect for daycare, park walks, and tiny adventures. Comes with a safety chest clip and soft padded straps.",
    price: 58,
    category: "bag",
    colors: ["Sand", "Sky Blue", "Cream"],
    sizes: ["One Size"],
    emoji: "🐰",
    cardColor: "#EED4BC",
  },
  {
    id: "7",
    slug: "muslin-swaddle-blanket",
    name: "Muslin Swaddle Blanket",
    description:
      "Lightweight 100% muslin cotton swaddle blanket — breathable, soft, and gets even softer with every wash. Ideal for swaddling, nursing cover, or tummy time mat.",
    price: 32,
    category: "blanket",
    colors: ["White & Mint", "White & Sand", "White & Sage"],
    sizes: ["120×120 cm"],
    emoji: "🌸",
    cardColor: "#C8E0D8",
  },
  {
    id: "8",
    slug: "long-sleeve-bodysuit-set",
    name: "Long Sleeve Bodysuit Set (3-Pack)",
    description:
      "Set of 3 long-sleeve organic bodysuits in coordinating neutral tones. Envelope neckline for easy dressing, flat seams inside to prevent irritation. A wardrobe staple.",
    price: 58,
    category: "body",
    colors: ["White", "Beige", "Sage"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    emoji: "👕",
    cardColor: "#D8E8E4",
    isNew: true,
  },
  {
    id: "9",
    slug: "duck-hooded-towel",
    name: "Duck Hooded Towel",
    description:
      "Extra-plush terry cotton hooded towel with a cute duck-beak hood detail. Ultra-absorbent and quick-drying. Sized generously to wrap toddlers snuggly after bath time.",
    price: 42,
    category: "towel",
    colors: ["White", "Cream", "Sand"],
    sizes: ["90×90 cm", "100×100 cm"],
    emoji: "🐥",
    cardColor: "#F0E4C8",
  },
  {
    id: "10",
    slug: "panda-zip-romper",
    name: "Panda Zip Romper",
    description:
      "Sweet panda-themed zip-up romper in soft fleece. Two-way zipper for easy diaper changes at night. Hood with panda ears makes every outing extra adorable.",
    price: 46,
    category: "romper",
    colors: ["White", "Cream", "Sage"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months"],
    emoji: "🐼",
    cardColor: "#DCDCDC",
    isNew: true,
  },
  {
    id: "11",
    slug: "gift-set-newborn",
    name: "Newborn Gift Set",
    description:
      "The perfect baby shower gift — 7-piece luxury set including a bodysuit, romper, blanket, bib, hat, mittens, and socks. Presented in a beautiful keepsake box.",
    price: 119,
    category: "set",
    colors: ["White", "Sage", "Sand"],
    sizes: ["0-1 Month", "1-3 Months"],
    emoji: "🎁",
    cardColor: "#E0D4C8",
  },
  {
    id: "12",
    slug: "diaper-bag-tote",
    name: "Organic Diaper Bag Tote",
    description:
      "Spacious and stylish diaper bag tote in organic canvas. 10 pockets including an insulated bottle holder and wipe-clean changing mat. Fits on stroller handles.",
    price: 94,
    category: "bag",
    colors: ["Beige", "Sage", "Sand"],
    sizes: ["One Size"],
    emoji: "👜",
    cardColor: "#D4CCBC",
  },
  {
    id: "13",
    slug: "knotted-gown-set",
    name: "Knotted Gown & Hat Set",
    description:
      "Classic newborn knotted gown with matching hat — the easiest outfit for those early weeks. Knot at the bottom means no fumbling with snaps during middle-of-the-night changes.",
    price: 36,
    category: "set",
    colors: ["White", "Cream", "Sky Blue", "Sand"],
    sizes: ["0-1 Month", "0-3 Months"],
    emoji: "🎩",
    cardColor: "#CCE0DC",
  },
  {
    id: "14",
    slug: "mini-explorer-backpack",
    name: "Mini Explorer Backpack",
    description:
      "A sturdy little backpack for curious toddlers ready to explore the world. Padded back panel, water-resistant lining, and a fun animal patch on the front.",
    price: 62,
    category: "bag",
    colors: ["Sky Blue", "Sage", "Sand"],
    sizes: ["One Size"],
    emoji: "🎒",
    cardColor: "#C8D8E8",
    isNew: true,
  },
  {
    id: "15",
    slug: "lion-hooded-romper",
    name: "Lion Hooded Romper",
    description:
      "The king of the nursery! Plush lion-mane hood romper in ultra-soft cotton fleece. Roar-worthy comfort with full-length zip for easy dressing. Perfect for chilly days and photo sessions.",
    price: 48,
    category: "romper",
    colors: ["Golden", "Cream", "Sand"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months", "12-18 Months"],
    emoji: "🦁",
    cardColor: "#EED4BC",
    isNew: true,
  },
  {
    id: "16",
    slug: "bamboo-pajama-set",
    name: "Bamboo Pajama Set (2-Piece)",
    description:
      "Silky-soft 70% bamboo, 30% organic cotton 2-piece pajama set — long-sleeve top and footed pants. Thermoregulating fabric keeps baby comfortable at any temperature. Machine washable, gets softer with every wash.",
    price: 54,
    category: "body",
    colors: ["White", "Sky Blue", "Sage", "Lavender"],
    sizes: ["0-3 Months", "3-6 Months", "6-9 Months", "9-12 Months", "12-18 Months"],
    emoji: "🌙",
    cardColor: "#D4CAE4",
    isNew: true,
  },
  {
    id: "17",
    slug: "organic-sleep-sack",
    name: "Organic Sleep Sack",
    description:
      "A safe, warm sleep environment for your baby — certified safer than loose blankets. 100% organic cotton with a 1.0 TOG warmth rating. Two-way zip for nighttime diaper changes without fully waking baby.",
    price: 44,
    category: "body",
    colors: ["White", "Sage", "Sand", "Sky Blue"],
    sizes: ["0-6 Months", "6-18 Months"],
    emoji: "😴",
    cardColor: "#C8DDD8",
  },
  {
    id: "18",
    slug: "rainbow-gift-set",
    name: "Rainbow Baby Gift Set",
    description:
      "A burst of soft pastel joy — 6-piece gift set with three bodysuits, a blanket, bib, and knot hat. Each piece in a different gentle rainbow shade. Presented in a keepsake gift box with ribbon.",
    price: 98,
    category: "set",
    colors: ["Pastel Rainbow", "Neutral Rainbow"],
    sizes: ["0-3 Months", "3-6 Months"],
    emoji: "🌈",
    cardColor: "#E8D8E8",
    isNew: true,
  },
  {
    id: "19",
    slug: "terry-poncho-towel",
    name: "Terry Poncho Towel",
    description:
      "A beach-to-bath hooded poncho towel for toddlers aged 1–4 years. Premium terry cotton, extra-absorbent, with a cheerful sun embroidery on the chest. Keeps little swimmers warm and cozy.",
    price: 46,
    category: "towel",
    colors: ["White", "Cream", "Sky Blue", "Sand"],
    sizes: ["1-2 Years", "2-4 Years"],
    emoji: "🏖️",
    cardColor: "#EDE4C0",
  },
  {
    id: "20",
    slug: "elephant-mini-bag",
    name: "Elephant Mini Backpack",
    description:
      "An adorably chunky elephant-shaped backpack with floppy ears and an embroidered trunk. Big enough for a snack, a toy, and all the essentials of a toddler adventure. Soft vegan leather-look fabric.",
    price: 56,
    category: "bag",
    colors: ["Grey", "Sage", "Blush"],
    sizes: ["One Size"],
    emoji: "🐘",
    cardColor: "#D8D8E8",
  },
];

/* Fabric per product (drives the fabric filter). Mirrors the DB backfill —
   kept here so the static fallback filters the same way as the live catalog. */
const fabricBySlug: Record<string, string> = {
  "organic-cotton-bodysuit": "cotton",
  "cloud-print-blanket": "cotton",
  "hospital-exit-set": "cotton",
  "bamboo-hooded-towel": "bamboo",
  "bear-ear-romper": "cotton",
  "mini-bunny-backpack": "other",
  "muslin-swaddle-blanket": "muslin",
  "long-sleeve-bodysuit-set": "cotton",
  "duck-hooded-towel": "terry",
  "panda-zip-romper": "cotton",
  "gift-set-newborn": "cotton",
  "diaper-bag-tote": "other",
  "knotted-gown-set": "cotton",
  "mini-explorer-backpack": "other",
  "lion-hooded-romper": "cotton",
  "bamboo-pajama-set": "bamboo",
  "organic-sleep-sack": "cotton",
  "rainbow-gift-set": "cotton",
  "terry-poncho-towel": "terry",
  "elephant-mini-bag": "other",
};

export const products: Product[] = baseProducts.map((p) => ({
  ...p,
  fabric: p.fabric ?? fabricBySlug[p.slug],
}));

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export const categoryLabels: Record<Product["category"], string> = {
  body: "Bodysuit",
  blanket: "Blanket",
  set: "Set",
  towel: "Towel",
  romper: "Romper",
  bag: "Bag",
  bathrobe: "Bathrobe",
  pajama: "Pajama Set",
  dress: "Dress",
  pants: "Pants",
  outerwear: "Outerwear",
  shoes: "Shoes",
  socks: "Socks",
  hat: "Hat",
  bib: "Bib",
  toy: "Toy",
  accessory: "Accessory",
};

/** Plural forms for filter pills / counts ("Dress" + s would be wrong). */
export const categoryPlurals: Record<Product["category"], string> = {
  body: "Bodysuits",
  blanket: "Blankets",
  set: "Sets",
  towel: "Towels",
  romper: "Rompers",
  bag: "Bags",
  bathrobe: "Bathrobes",
  pajama: "Pajama Sets",
  dress: "Dresses",
  pants: "Pants",
  outerwear: "Outerwear",
  shoes: "Shoes",
  socks: "Socks",
  hat: "Hats",
  bib: "Bibs",
  toy: "Toys",
  accessory: "Accessories",
};
